Repository isabellevillasenor/crate, pull requests merged in 2021-04, with the labels that each got.

#53 Be queries2
  code/api/src/modules/product/resolvers.js
  code/api/src/modules/product/types.js
  code/api/src/modules/user/query.js
  code/api/src/modules/user/resolvers.js
  code/api/src/modules/userProducts/types.js
Labels: BE, MVP

#49 Gaj/feature/subscriptions format
  code/web/cypress/integration/Subscription_spec.js
  code/web/src/modules/subscription/api/actions.js
  code/web/src/modules/user/MyAccount.js
  code/web/src/modules/user/Subscriptions.js
Labels: FE, MVP, Testing

#55 Reb/testing my account
  code/package.json
  code/web/cypress/integration/myAccount_spec.js
  code/web/cypress/plugins/index.js
  code/web/src/modules/user/MyAccount.js
  config/config.json
Labels: FE, Testing
